upgrades:
  auto_sell:
    - 25000.234
  auto_pickup:
    - 10000.123
  auto_plant:
    - 30000.3532
  multiplier:
    - 20000.23
    - 30000.234
    - 40000.5425
    - 50000.234

multiplier_rates:
  - 2.5
  - 3.7
  - 5.6
  - 10.3

prices:
  POTATO: 1.4
  WHEAT: 2.3
  WHEAT_SEEDS: 3.1
  CARROT: 4.6
  BEETROOT_SEEDS: 5.3
  BEETROOT: 6.6

xp:
  POTATOES: 1
  BEETROOTS: 2
  WHEAT: 3
  CARROTS: 4

seeds:
  WHEAT: WHEAT_SEEDS
  BEETROOTS: BEETROOT_SEEDS
  CARROTS: CARROT
  POTATOES: POTATO