upgrades:
  auto_sell:
    - 25000
  auto_pickup:
    - 10000
  auto_plant:
    - 30000
  multiplier:
    - 20000
    - 30000
    - 40000
    - 50000

multiplier_rates:
  - 2.5
  - 3.7
  - 5.6
  - 10.3

prices:
  POTATO: 1
  WHEAT: 2
  WHEAT_SEEDS: 3
  CARROT: 4
  BEETROOT_SEEDS: 5
  BEETROOT: 6

xp:
  POTATOES: 1
  BEETROOTS: 2
  WHEAT: 3
  CARROTS: 4

seeds:
  WHEAT: WHEAT_SEEDS
  BEETROOTS: BEETROOT_SEEDS
  CARROTS: CARROT
  POTATOES: POTATO