main: io.github.itstaylz.sakurabranch.SakuraBranch
name: Sakurabranch
version: '${project.version}'
authors: [ itsTaylz ]
api-version: 1.18
depend: [Hexlib, Vault]
commands:

  sakurabranch:
    permission: sakurabranch.givecommand
    permission-message: §cNo permission

  sakurabranchreload:
    permission: sakurabranch.reload
    permission-message: §cNo permission
